version: "3"
services:
# Database
  DB_Services:
    build:
      context: .
      dockerfile: DB_MySQL/DB_MySQL.Dockerfile
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
      - ./DB_MySQL/DB_Data:/var/lib/mysql
    image: mysql:5.7
    ports:
      - '3333:3306'
    expose:
      - '3333'
# JAVA Spring
  AP_Services:
    build:
      context: .
      dockerfile: AP_Spring/AP_Spring.Dockerfile
    image: openjdk:8-jdk-alpine
    ports:
      - "8080:8080"