version: "3"
services:
# Database
  DB_Services:
    build:
      context: .
      dockerfile: DB_MySQL/DB_MySQL.Dockerfile
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
      - ./DB_MySQL/DB_Data:/var/lib/mysql
    image: mysql:5.7
    ports:
      - '3333:3306'
    expose:
      - '3333'
# JAVA Spring
  Front_WEB:
    build:
      context: .
      dockerfile: Front_WEB/Front_WEB.Dockerfile
    image: node:14.16
    ports:
      - "3500:3000"
    depends_on:
      - API_MBTI
      - API_User